### ISSUE TITLE
Bitbucket, GitLab and VSTS integration improvements

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#2411]
* Bitbucket
  * [ ] Pull requests - https://github.com/appveyor/ci/issues/736
  * [ ] OAuth 2.0 - https://github.com/appveyor/ci/issues/1277
  * [ ] Teams security - https://github.com/appveyor/ci/issues/41
  * [ ] Stride notifications - https://github.com/appveyor/ci/issues/2071
  * [ ] Rename Stash - https://github.com/appveyor/ci/issues/1924
  * [ ] Tags for Mercurial repos - https://github.com/appveyor/ci/issues/1095
  * [ ] Deployment to download resources - https://github.com/appveyor/ci/issues/735
* VSTS
  * [ ] Commit filtering - https://github.com/appveyor/ci/issues/2403
  * [ ] Pull requests - https://github.com/appveyor/ci/issues/1784
  * [ ] Marketplace extensions to download artifacts for release management - https://github.com/appveyor/ci/issues/2308
  * [ ] Git clone - https://github.com/appveyor/ci/issues/1630
* GitLab
  * [ ] Commit filtering - https://github.com/appveyor/ci/issues/2402
  * [ ] Merge requests - https://github.com/appveyor/ci/issues/651
  * [ ] GitLab sign in button - https://github.com/appveyor/ci/issues/2409
  * [ ] On-premise GitLab support - https://github.com/appveyor/ci/issues/711
